version: "3.9"

services:
    api:
        container_name: fastapi
        restart: always
        build: .
        working_dir: /code/app
        command: uvicorn main:app --host 0.0.0.0 --reload
        volumes:
            - .app:/code/app
        ports:
            - 8000:8000
